##
## EPITECH PROJECT, 2020
## Makefile
## File description:
## Makefile
##

all:
		make -C ./Ncurse
		make -C ./Sfml
		make -C ./SDL

clean:
		make clean -C ./Ncurse
		make clean -C ./Sfml
		make clean -C ./SDL

fclean:		clean
		make fclean -C ./Ncurse
		make fclean -C ./Sfml
		make fclean -C ./SDL
re:		fclean all
