<div class="container header">
      <nav class="nav-header">
        <a href="index.php"><img class="logo logo-header" src="img/logo.png" alt="Logo"></a>
        <a class="anime" href="etude.php"><i class="fa fa-book fan" aria-hidden="true"></i>Etudes & Expériences professionnelles</a>
        <a class="anime" href="diplome.php"><i class="fa fa-columns fan" aria-hidden="true"></i>Diplômes</a>
        <ul class="ul-a anime">
          <li>
            <a id="more" href="#"><i class="fa fa-cubes fan" aria-hidden="true"></i>Passions<i class="fa fa-sort-desc" aria-hidden="true"></i></a>
            <ul id="hidden-element" class="hidden position">
              <li><a href="sport.php">Sports</a></li>
              <li><a href="manga.php">Manga</a></li>
            </ul>
          </li>
        </ul>
        <a class="anime page" href="contact.php"><i class="fa fa-envelope fan" aria-hidden="true"></i>Contactez-Moi</a>
      </nav>
    </div>
  </header>
  <main>
    <div class="main-header container-main">
      <section class="alpha">
      </section>
      <section class="delta">
        <a href="contact.php"><h1 class="title">Contactez-Moi</h1></a>
        <div class="contact">
          <article class="art art-contact">
            <h2 class="title2">Téléphone</h2>
            <p>06 40 62 78 76</p>
          </article>
          <article class="art art-contact">
            <h2 class="title2">Email</h2>
            <a href="mailto:bryanice@hotmail.fr">bryanice@hotmail.fr</a>
          </article>
          <article class="art art-contact">
            <h2 class="title2">Courrier</h2>
            <p>54 bd henri sappia La Séréna D<br>06100 Nice</p>
          </article>
        </div>
      </section>
    </div>
  </main>