    <div class="container header">
      <nav class="nav-header">
        <a href="index.php"><img class="logo logo-header" src="img/logo.png" alt="Logo"></a>
        <a class="anime page" href="etude.php"><i class="fa fa-book fan" aria-hidden="true"></i>Etudes & Expériences professionnelles</a>
        <a class="anime" href="diplome.php"><i class="fa fa-columns fan" aria-hidden="true"></i>Diplômes</a>
        <ul class="ul-a anime">
          <li>
            <a id="more" href="#"><i class="fa fa-cubes fan" aria-hidden="true"></i>Passions<i class="fa fa-sort-desc" aria-hidden="true"></i></a>
            <ul id="hidden-element" class="hidden position">
              <li><a href="sport.php">Sports</a></li>
              <li><a href="manga.php">Manga</a></li>
            </ul>
          </li>
        </ul>
        <a class="anime" href="contact.php"><i class="fa fa-envelope" aria-hidden="true"></i>Contactez-Moi</a>
      </nav>
    </div>
  </header>
  <main>
    <div class="main-header container-main">
      <section class="alpha">
      </section>
      <section class="delta">
        <a href="etude.php"><h1 class="title">Etudes & Expériences professionnelles</h1></a>
        <article class="art">
          <h2 class="title2">2017-2018 : Formation 3WAcademy</h2>
          <p>J'ai suivi une formation Développeur Intégrateur Web pendant 3 mois. La formation s'est deroulée en ligne. J'ai appris differents langages: HTML, CSS, JavaScript et PHP. J'ai aussi appris à utiliser les méthodes: Bootstrap, Wordpress, JQuery, SVG, Canvas.</p>
        </article>
        <article class="art">
          <h2 class="title2">2016-2017 : Elis Linger</h2>
            <p>J'ai travaillé dans l'entreprise Elis pendant 6 mois dans les hôpitaux en tant que linger. En travaillant seul j'ai appris à être autonome. J'étais chargé de remplir les armoires et faire les commandes de linge.</p>
        </article>
        <article class="art">
          <h2 class="title2">2013-2016 : Carrossier Peintre</h2>
          <p>J'ai eu mon CAP Carrossier dans le lycée professionnel Don Bosco à Nice. J'ai fait trois stages en entreprise d'une durée de 15 semaines. J'ai ensuite réussi mon CAP Peintre en carrosserie dans le même lycée. Pendant cette année d'apprentissage j'ai pu travailler dans l'entreprise Bendix à Nice.</p>
        </article>
      </section>
    </div>
      
      