<!DOCTYPE html>
<html lang="fr">
<head>
  <title>Porte-Folio Fortin.B</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width">
  <script src="https://use.fontawesome.com/0186f6ba39.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Bellefair|Cormorant+Upright" rel="stylesheet">
  <script 
  src="https://code.jquery.com/jquery-3.2.1.min.js" 
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
  <script src="js/jquery.flexslider.js"></script>
  <script src="js/ajax.js"></script>
  <script src="js/events.js"></script>
  <link rel="stylesheet" href="css/flexslider.css" type="text/css">
  <link rel="stylesheet" href="css/normalize-3.0.3.min.css"> 
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="css/responsive.css">
  <link rel="stylesheet" href="css/animated.css">
</head>
<body>
  <header>
  
        
        
        
  <?php include $template . '.phtml'; ?>    
  </main>
  <footer>
    <div class="container footer">
      <a href="index.php"><img class="logo logo-header" src="img/logo.png" alt="Logo"></a>
      <p>Voici mon Porte-Folio qui me permettra, je l'espère, d'obtenir mon diplôme <b>Apprenti Developpeur Intégrateur Web</b>. J'ai passé ma formation à la <i><a class="footer-lien" href="https://3wa.fr/">3WAcademy</a><i/>. Ceci est mon premier site, si vous voulez plus d'informations veuillez me <a class="footer-lien" href="mailto:bryanice@hotmail.fr">"Contacter par email"</a> ou pour plus d'information <a class="footer-lien" href="contact.php">"Ici"</a>. J'espère que vous avez aimé mon site et je vous souhaite une bonne journée.</p>
    </div>
  </footer>
  <script src="js/main.js"></script>
</body>
</html>