##
## EPITECH PROJECT, 2020
## Makefile
## File description:
## Makefile
##

all:
		make -C ./Menu
		make -C ./Nibbler
		make -C ./Packman
		make -C ./Loose
		make -C ./Win

base:
		make -C ./Menu
		make -C ./Loose
		make -C ./Win

clean:
		make clean -C ./Menu
		make clean -C ./Nibbler
		make clean -C ./Packman
		make clean -C ./Loose
		make clean -C ./Win

fclean:		clean
		make fclean -C ./Menu
		make fclean -C ./Nibbler
		make fclean -C ./Packman
		make fclean -C ./Loose
		make fclean -C ./Win

re:		fclean all